name: Docker Build & Push with Maven (clean&install)

on:
  push:
    branches: [ master ]

jobs:
  build_and_push_docker:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Clean and Install with Maven
        run: mvn clean install -Dmaven.test.skip=true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          # You need to add your docker username and password in the repository secret
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          # You need to add YOUR_DOCKER_ACCOUNT_NAME here
          tags: YOUR_DOCKER_ACCOUNT_NAME/open-ai-chat:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
